"""create analyses and media files

Revision ID: e58c4d97c70a
Revises: 
Create Date: 2026-08-19 17:39:27.654831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58c4d97c70a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('original_sha256', sa.String(length=64), nullable=False),
    sa.Column('original_storage_key', sa.String(length=512), nullable=False),
    sa.Column('format_name', sa.String(length=255), nullable=False),
    sa.Column('codec_name', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('frame_rate', sa.Float(), nullable=False),
    sa.Column('pix_fmt', sa.String(length=32), nullable=True),
    sa.Column('constant_frame_rate', sa.Boolean(), nullable=False),
    sa.Column('was_normalized', sa.Boolean(), nullable=False),
    sa.Column('derivative_storage_key', sa.String(length=512), nullable=False),
    sa.Column('derivative_sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_analysis_id'), 'media_files', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_files_analysis_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_table('analyses')
    # ### end Alembic commands ###
